services:
  postgres:
    image: postgres:17

    container_name: supportsense-postgres

    environment:
      POSTGRES_USER: supportsense
      POSTGRES_PASSWORD: password
      POSTGRES_DB: supportsense

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: